"""add_question_notifications_table

Revision ID: 171f376a3248
Revises: 7d491bcb3ecb
Create Date: 2025-08-11 15:07:45.102148

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '171f376a3248'
down_revision = '7d491bcb3ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_id', 'question_id', 'sender_user_id', 'recipient_user_id', name='unique_question_notification')
    )
    op.create_index(op.f('ix_question_notifications_id'), 'question_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_notifications_id'), table_name='question_notifications')
    op.drop_table('question_notifications')
    # ### end Alembic commands ###
