"""Add GPT tasks table

Revision ID: add_gpt_tasks_table
Revises: 9f3b1c2d4a67
Create Date: 2025-08-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_gpt_tasks_table'
down_revision = '9f3b1c2d4a67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpt_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('RELATIONSHIP_ANALYSIS', 'MOOD_ANALYSIS', 'QUESTION_GENERATION', 'FEEDBACK_ANALYSIS', 'CUSTOM_ANALYSIS', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('anthropic_calls', sa.Integer(), nullable=True),
    sa.Column('internal_api_calls', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpt_tasks_id'), 'gpt_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpt_tasks_id'), table_name='gpt_tasks')
    op.drop_table('gpt_tasks')
    # ### end Alembic commands ###
